### ISSUE TITLE
How to use this.

### ISSUE THREAD

**Issue by yangsia** [biolab/orange-translations#62]
Is this project a add-on of orange3?
How to use it?
How to create other languages translations? Anyone has a guide about it?

**Comment by janezd** [comment]
This repo contains translation of Orange to Slovenian language. It is somewhat provisional and may change its form in the future, but in backward-compatibilish way - no work done will be lost, but files may be renamed or moved.

It can be used to translate Orange to other languages. I added a short README. If you are computer scientist (at this point in development it requires some knowledge) and you're willing to invest time, you should be able to do it. If you're serious about it, I can assist you. I wouldn't like to help you install conda and create environment, but if you have no problems with this and only encounter something, say, related to running trubar, I'd be happy to help.
